---
  - name: Start Nginx
    become: yes
    service: name=nginx state=started

  - name: Reload Nginx
    become: yes
    service: name=nginx state=reloaded

  - name: Restart Nginx
    become: yes
    service: name=nginx state=restarted

  - name: Reload PHPFPM
    become: yes
    service: name=php7.1-fpm state=reloaded
