---

- name: Create the {{ goapp_path }} app folder
  file: path={{ goapp_path }}
        owner=forge
        group=forge
        mode=0774
        state=directory

- name: Setup the Git repo
  git: repo=git@github.com:codeddesign/video-tracker.git dest={{ goapp_path }} accept_hostkey=yes

- name: Build the Go application {{ goapp_path }}
  command: chdir={{ goapp_path }} /usr/local/go/bin/go get
  environment: "{{ goapp_environment }}"

- name: Create the systemd service
  become: yes
  template: src=video-tracker.service.j2
            dest=/etc/systemd/system/video-tracker.service

- name: Enable the systemd service
  become: yes
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: video-tracker
