---
- hosts: ad3production
  vars_files:
    - vars/secrets.yaml
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_config:
      tags: "env:production"
