---
- hosts: ad3production
  vars_files:
    - vars/datadog-api.yaml
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ api_key }}"
    datadog_config:
      tags: "production"
