---
- hosts: "{{ host | default('ad3production') }}"
  vars_files:
    - vars/{{ env | default('production') }}.yaml
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{ dd_api_key }}"
    datadog_config:
      tags: "env:{{ env | default('production') }}"
    datadog_checks:
      go_expvar:
        init_config:
        instances:
          - expvar_url: http://localhost:5000/debug/vars
            namespace: video-tracker
            metrics:
              - path: events_processed
                type: rate
              - path: events_pipelined
                type: rate
      php_fpm:
        init_config:
        instances:
          - status_url: http://localhost/status
            ping_url: http://localhost/ping
